### ISSUE TITLE
Support for EfCore with PostgreSQL?

### ISSUE THREAD

**Issue by zewa1999** [SimonCropp/Delta#198]
Hi, I want to congratulate you on the good work that you have done with this package.

Any further milestone to be able to use it with Postgresql database?

As I saw from you documentation, you only support EF with SqlServer.

Thank you!

**Comment by SimonCropp** [comment]
looks like pg_last_committed_xact  would work as an etag https://stackoverflow.com/a/65340830/53158

**Comment by mwo-dk** [comment]
Or maybe: https://www.npgsql.org/efcore/modeling/concurrency.html?tabs=data-annotations?

**Comment by Neo-vortex** [comment]
Postgres does not support "Change tracking "

**Comment by Kurpanik** [comment]
Couldn't this be solved with Triggers?

**Comment by SimonCropp** [comment]
postrgres support has been added

**Comment by edcsu** [comment]
Thanks for adding this support.

**Comment by SimonCropp** [comment]
has anyone tried this? any issues/problems to report?

**Comment by Kurpanik** [comment]
Not yet. But since support for Postgres has been added, I plan to integrate it into one of my projects soon.

**Comment by SimonCropp** [comment]
@edcsu can u share some before and after numbers?

**Comment by edcsu** [comment]
> [@edcsu](https://github.com/edcsu) can u share some before and after numbers?

I reproduced the effect locally.
I am querying fro 1000 products.
### Before using delta

<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/1e3ae1fb-023b-404e-8ec8-198ca271b086" />
### Using delta initial request

<img width="1230" alt="Image" src="https://github.com/user-attachments/assets/2031f8bf-2675-4471-9da8-c7a49852f222" />
### Subsequent request 1

<img width="1244" alt="Image" src="https://github.com/user-attachments/assets/601692c4-6a79-4fa6-8bbf-d27c7d830810" />
### next request

<img width="1236" alt="Image" src="https://github.com/user-attachments/assets/2435f101-21d9-488a-983b-67abefe3af14" />
### another

<img width="1233" alt="Image" src="https://github.com/user-attachments/assets/a7c4cc2b-1b9f-47c7-b470-1e8e21be7472" />

**Comment by SimonCropp** [comment]
@edcsu that is a great outcome.

**Comment by edcsu** [comment]
> [@edcsu](https://github.com/edcsu) that is a great outcome.

Indeed it is because we are dealing with millions of records.
🚀 Just wanted to say thanks for both Delta and replicant.
They are both incredibly fast and optimised. 
Really appreciate the attention to performance. 
Great work!
