### ISSUE TITLE
Does delta support for microservices?

### ISSUE THREAD

**Issue by viveknuna** [SimonCropp/Delta#199]
Here’s the corrected version of your text with improved grammar and structure:

---

First of all, apologies for raising this as a bug, as it’s not. I wanted to have a discussion or get your opinion on this.

We work in a microservices-based architecture. We have an ASP.NET Core web application that communicates with another service through Azure Service Bus. From there, it interacts with additional services, and so on. This entire architecture supports multitenancy, where we have separate databases for each tenant, but each database is shared among all the services.

Given this setup, would using Delta really be beneficial in our case? Does it work effectively across multiple services, especially considering that not all services are web APIs?

---

Let me know if you need further refinements!

@SimonCropp

**Comment by SimonCropp** [comment]
does this help https://github.com/SimonCropp/Delta?tab=readme-ov-file#programmatic-client-usage  ?
