### ISSUE TITLE
Delta.EF NET 8 Support Issue

### ISSUE THREAD

**Issue by VictorM88** [SimonCropp/Delta#205]
The latest update, 5.2.0 was supposed to add the ability to use the package with NET 8 as well.
It seems that this is not the case for Delta.EF: https://www.nuget.org/packages/Delta.EF#supportedframeworks-body-tab
![image](https://github.com/user-attachments/assets/22940959-8bf4-4d55-a9ea-8b172cf2b902)

As you can see the package has dependencies of NET 9 packages.

Is there any way around this?

**Comment by SimonCropp** [comment]
>  the package has dependencies of NET 9 packages

Delta has a dependency on EF 9. Not NET 9. 

EF 9 supports NET 8

![image](https://github.com/user-attachments/assets/a431ec02-c7ca-4f84-8da9-2bb75c2da645)

**Comment by VictorM88** [comment]
You are right, I misread. Thanks!
