### ISSUE TITLE
There a dependency mismatch version on the package Detal.EF

### ISSUE THREAD

**Issue by josedr120** [SimonCropp/Delta#208]
The package says is supported on .net 8, but the depedencies of ef core are on version 9 not eight, that causing a issue on installing this package on .net 8 projects
![Screenshot 2024-11-29 104117](https://github.com/user-attachments/assets/60b0ab39-47b7-4dee-9227-30b374e52320)

**Comment by SimonCropp** [comment]
ef 9 support .net 8

**Comment by SimonCropp** [comment]
if you want to continue using ef 8. then Delta v3 supports it https://www.nuget.org/packages/Delta/3.0.3#dependencies-body-tab
