### ISSUE TITLE
Question on usage if projections are in place on EF Queries

### ISSUE THREAD

**Issue by funkel1989** [SimonCropp/Delta#209]
So, I've read the readme and watched a few YouTube videos demonstrating this package and I'm still a bit confused on how it works so I'm going to just ask my question.

We have a react app that supports a metric dashboard with many different calculations on it for our user base.

We use Expressions with EFCore to query our database and this allows us to create projections of data in the table based on how we are using it.  The expression is translated into a Raw SQL strings kind of like a stored procedure is being executed so all of the work occurs on the database but EFCore is still doing this translation. I'm sure this is all a bit confusing without actually seeing what we've built but hopefully it's enough to answer my question:

Will your package benefit me with query caching at all? We do have tracking enabled but the raw data is never actually returned to the db context, only projections of the raw data.

If this is confusing, I can try to post some examples we have but unfortunately I can't expose much of the code publicly.

**Comment by SimonCropp** [comment]
Delta works based on a db level incrementing counter. so it works irrespective of what and how you are querying

as long as you are Using either [SQL Server Change Tracking](https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/track-data-changes-sql-server) and/or [SQL Server Row Versioning](https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql)

 https://github.com/SimonCropp/Delta?tab=readme-ov-file#assumptions

**Comment by frasermclean** [comment]
Do all tables need to have Row Versioning enabled? I am also using an object which pulls data from 3 tables but I am not getting any 304 responses.

**Comment by SimonCropp** [comment]
> Do all tables need to have Row Versioning enabled

yes, for all the tables u want to be included in the 304 check
