### ISSUE TITLE
classic mvc controller case

### ISSUE THREAD

**Issue by kodlar** [SimonCropp/Delta#210]
Hi Simon I need a specific endpoint using delta instead of  app.UseDelta() also in my case I am using classic mvc controller which lead us to  app.MapControllers(); How can we customize for specific endpoint.

Thanks

**Comment by AcademicHumber** [comment]
You can configure the endpoints that will run Delta's middleware.
```csharp
app.UseDelta(
    shouldExecute: httpContext =>
    {
        var path = httpContext.Request.Path.ToString();
        return path.Contains("match");
    });
```

**Comment by SimonCropp** [comment]
@AcademicHumber is correct
